version: 2
updates:

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/oneapp-server/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/oneapp-web/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
