version: 1
update_configs:
  
  # Base package
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
  
  # Server component
  - package_manager: "javascript"
    directory: "/oneapp-server"
    update_schedule: "weekly"
  
  # Web component
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"