# To fetch schema from
introspection: http://localhost:4000

servers:
  - url: https://usds-nj-oneapp-staging-api.app.cloud.gov
    description: USDS Staging

info:
  title: NJ OneApp GraphQL Server
  description: >
    New Jersey OneApp back-end server re-implemented as a GraphQL server.
    

    When running the GraphQL server locally, the server can be started with the command `yarn serve:mock` to return dummy data (helpful when developing against queries not yet implemented.) 

domains:
  - name: Server Information
    description: Understand the current running version of the server 
    usecases:         
      - name: Fetch version
        description: Check the Git commit information the server was built from
        query: query._version
  
  - name: Authentication
    description: Register and login a user into OneApp
    usecases:
      - name: Check if username is available
        description: Checks the database if the username has been registered before
        query: query.users
        select: userAvailable
        expand: userAvailable
      - name: Register user
        description: 'Create a new account for the user. The JWT can then be used as an `Authentication: Bearer <token>`.'
        query: mutation.userRegister
      - name: Login user
        description: 'Login an existing user. The JWT can then be used as an `Authentication: Bearer <token>`.'
        query: mutation.userAuthenticate
  
  - name: Forgot Credentials
    description: When the user forgets their login information
    usecases:
      - name: Fetch a user's hint question
        description: The hint question is needed to determine what to the ask the user when resetting their password
        query: query.users
        select: userPasswordHintQuestion
      - name: Reset a user's password
        description: Using the user's response to their hint question, generate a send the user a new password at their email address
        query: mutation.userPasswordReset
  
  - name: Translations
    description: Look up translation values for fields. All queries through the entire application support the `Accept-Language` header to return correctly translated values.
    usecases:
      - name: Lookup a single translation value
        description: Helpful for return the phrases for error messages, etc.
        query: query.translation
      - name: Lookup multiple translation values
        description: This will return all available languages if no `TEXT_IDS` are provided, but can be filtered down by passing one more more `TEXT_ID` values.
        query: query.translations
  
  - name: OneApp Application
    description: Work with an in-progress application
    usecases:
      - name: Fetch the user's application
        description: Return the user's current application in whatever state was last saved to the server
        query: query.application
        expand: contact,foodStampInfo,programInfo,tanfGaHeader
      - name: Persist the user's application
        description: >
          Perform an upsert of the user's application. The back-end server will determine how to persist this to the Oracle database via stored procedures.


          **Note:** To submit a SNAP application, the existing stored procedures' expect an item of `{CODE_TYPE: 'FI', CODE: 'FI', HAVE_THIS: true}`. This indicates this is a SNAP application.
        query: mutation.applicationUpdate
      - name: Send the user's application
        description: >
          Sends the users' application to UAP for processing


          **Note:** The `APPLICATION_NUMBER` will change after sending the application. You will need the `APPLICATION_NUMBER` to get the confirmation team.
        query: mutation.applicationSend
      - name: Display the user's application confirmation
        description: Returns all the information the user needs to confirm their application has been received
        query: query.applicationConfirmation
  
  - name: NJ Locations
    description: Lookup New Jersey location information. There are also helpful queries for pre-populate user's county.
    usecases:
      - name: Fetch all NJ counties
        description: Useful for populating dropdowns
        query: query.counties
      - name: Verify a zipcode exists in New Jersey
        description: Given a zipcode, checks if the zipcode is a valid New Jersey USPS zipcode
        query: query.isValidNJZipcode
      - name: Fetch a user's county information
        description: After persisting the user's address via the `mutation.applicationUpdate` query, this query will return the county information for user. This allows the UI to pre-select and guess the county in the dropdown without making the user pick their county.
        query: query.getCountyDetails
      - name: USPS address details
        description: Confirm the address exists in the USPS's database and the formatting is correct. If an address does not exist and error will be returned.
        query: query.getAddressDetails

  - name: Eligibility Calculations
    description: Check the eligibility of an application for each safety net program.
    usecases:
      - name: Check eligibility for food stamp program
        description: Returns results of income tests and food stamp benefits
        query: query.application
        expand: eligibility
      - name: (DEPRECATED) Check eligibility for Family Care (Medicaid) program
        description: (DEPRECATED) Returns results of Family Care (Medicaid) test and amount
        query: query.application
        expand: fcEligibility
      - name: Check eligibility for TANF program
        description: Returns results of TANF test and amount
        query: query.application
        expand: tfEligibility
      - name: Check eligibility for General Assistance program
        description: Returns results of GA test and amount
        query: query.application
        expand: gaEligibility